name: Build and Test (SBT)

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 21
      uses: actions/setup-java@v6
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Set up SBT
      uses: sbt/setup-sbt@v1
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --add github.actor OndrejSpanel
        git config --add github.token ${{ secrets.GITHUB_TOKEN }}
        sbt projsJVM/test projsJS/test
