name: Build and Test (SBT)

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --add github.actor OndrejSpanel
        git config --add github.token ${{ secrets.GITHUB_TOKEN }}
        sbt projsJVM/test projsJS/test
