name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERTOKEN: ${{ secrets.GITHUB_USERTOKEN }}
        run: |
          git config --add github.actor OndrejSpanel
          git config --add github.token ${{ secrets.GITHUB_TOKEN }}
          sbt projsJS/fullOptJS
          mkdir public
          cp js/target/scala-2.12/scalafromjs-opt.js public/.
          cp js/target/scala-2.12/index.html public/.
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
