name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v7
      - name: Set up JDK 21
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set up SBT
        uses: sbt/setup-sbt@v1
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --add github.actor OndrejSpanel
          git config --add github.token ${{ secrets.GITHUB_TOKEN }}
          sbt projsJS/fullOptJS
          mkdir public
          cp js/target/scala-2.13/scalafromjs-opt.js public/.
          cp js/target/scala-2.13/index.html public/.
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: gh-pages
          build_dir: public

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
